name = "PrettyNumbers"
uuid = "d1bdb62b-d559-469f-b147-fd8a93502a34"
license = "MIT"
desc = "Pretty print numbers in Julia"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.2.0"

[compat]
julia = "^1.6"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
